#!/usr/bin/env python3
"""Regenerate docs/prompt-templates.md from .cursor/skills/*/SKILL.md frontmatter."""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SKILLS_DIR = ROOT / ".cursor" / "skills"
OUT = ROOT / "docs" / "prompt-templates.md"
REQUIRED = ("name", "summary", "user-prompt", "category")

# 分類の表示順（未定義は末尾、名前順）
CATEGORY_ORDER: dict[str, int] = {
    "環境": 1,
    "UI・要件": 2,
    "Git・PR": 3,
}


def read_frontmatter(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    match = re.match(r"^---\r?\n(.*?)\r?\n---", text, re.DOTALL)
    if not match:
        raise ValueError(f"No YAML frontmatter: {path}")

    data: dict[str, str] = {}
    key: str | None = None
    parts: list[str] = []

    def flush() -> None:
        nonlocal key, parts
        if key is not None:
            data[key] = " ".join(parts).strip().strip('"').strip("'")
        key = None
        parts = []

    for line in match.group(1).splitlines():
        key_match = re.match(r"^([a-z0-9_-]+):\s*(.*)$", line)
        if key_match:
            flush()
            key = key_match.group(1)
            rest = key_match.group(2).strip()
            if rest in (">-", ">", "|", "|-"):
                parts = []
            elif rest:
                parts = [rest.strip('"').strip("'")]
            else:
                parts = []
        elif key and (line.startswith("  ") or line.startswith("\t")):
            parts.append(line.strip())
        elif key and line.strip():
            parts.append(line.strip())

    flush()
    return data


def esc_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def category_sort_key(category: str) -> tuple[int, str]:
    return (CATEGORY_ORDER.get(category, 999), category)


def main() -> int:
    skill_files = sorted(SKILLS_DIR.glob("*/SKILL.md"))
    if not skill_files:
        print(f"ERROR: no skills under {SKILLS_DIR}", file=sys.stderr)
        return 1

    rows: list[tuple[str, str, str, str]] = []
    for skill_md in skill_files:
        frontmatter = read_frontmatter(skill_md)
        missing = [field for field in REQUIRED if not frontmatter.get(field)]
        if missing:
            print(f"ERROR {skill_md}: missing frontmatter {missing}", file=sys.stderr)
            return 1
        rows.append(
            (
                frontmatter["category"],
                frontmatter["name"],
                frontmatter["summary"],
                frontmatter["user-prompt"],
            )
        )

    rows.sort(key=lambda row: (category_sort_key(row[0]), row[1]))

    lines = [
        "<!-- generated by scripts/sync-skill-prompt-table.py -->",
        "",
        "| 項番 | 分類 | スキル名 | スキルの内容 | スキルを使うときの指示文 |",
        "|-----|------|---------|-------------|------------------------|",
    ]
    for index, (category, name, summary, prompt) in enumerate(rows, start=1):
        lines.append(
            f"| {index} | {esc_cell(category)} | `{name}` | {esc_cell(summary)} | {esc_cell(prompt)} |"
        )
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({len(rows)} skills)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
