#!/usr/bin/env python3
"""Generate frontend/src/lib/types.ts from backend Pydantic schemas."""

from __future__ import annotations

import argparse
import sys
import types
import typing
from datetime import datetime
from enum import StrEnum
from pathlib import Path
from uuid import UUID

ROOT = Path(__file__).resolve().parents[1]
BACKEND = ROOT / "backend"
OUTPUT = ROOT / "frontend" / "src" / "lib" / "types.ts"

sys.path.insert(0, str(BACKEND))

from app.core.status import JobStatus  # noqa: E402
from app.schemas.research import (  # noqa: E402
    AmazonCandidateResponse,
    CreateResearchResponse,
    ExportJobResponse,
    JobError,
    ResearchJobResponse,
    ReviewItemResponse,
    ReviewItemsPageResponse,
    SellerSummary,
)

HEADER = """\
// AUTO-GENERATED by scripts/sync-api-types.py — do not edit by hand.
// Regenerate: python3 scripts/sync-api-types.py

"""

TS_NAMES: dict[str, str] = {
    "ResearchJobResponse": "ResearchJob",
    "AmazonCandidateResponse": "AmazonCandidate",
    "ReviewItemResponse": "ReviewItem",
    "ReviewItemsPageResponse": "ReviewItemsPage",
}


def unwrap_optional(annotation: object) -> tuple[object, bool]:
    origin = typing.get_origin(annotation)
    if origin is typing.Union or origin is types.UnionType:
        args = [a for a in typing.get_args(annotation) if a is not type(None)]
        if len(args) == 1:
            return args[0], True
    return annotation, False


def python_type_to_ts(annotation: object, *, models: dict[str, type]) -> str:
    annotation, optional = unwrap_optional(annotation)
    origin = typing.get_origin(annotation)

    if origin is list:
        inner = typing.get_args(annotation)[0]
        ts = f"{python_type_to_ts(inner, models=models)}[]"
    elif isinstance(annotation, type) and issubclass(annotation, StrEnum):
        ts = "JobStatus"
    elif annotation is UUID:
        ts = "string"
    elif annotation is str:
        ts = "string"
    elif annotation is int:
        ts = "number"
    elif annotation is float:
        ts = "number"
    elif annotation is bool:
        ts = "boolean"
    elif annotation is datetime:
        ts = "string"
    elif hasattr(annotation, "model_fields"):
        ts = TS_NAMES.get(annotation.__name__, annotation.__name__)
    else:
        ts = "unknown"

    if optional:
        ts = f"{ts} | null"
    return ts


def render_interface(model: type, models: dict[str, type]) -> str:
    name = TS_NAMES.get(model.__name__, model.__name__)
    lines = [f"export interface {name} {{"]
    for field_name, field in model.model_fields.items():
        ts_type = python_type_to_ts(field.annotation, models=models)
        lines.append(f"  {field_name}: {ts_type};")
    lines.append("}")
    return "\n".join(lines)


def render_job_status() -> str:
    values = " | ".join(f'"{member.value}"' for member in JobStatus)
    return f"export type JobStatus =\n  | {values.replace(' | ', '\n  | ')};"


def generate() -> str:
    models = {
        cls.__name__: cls
        for cls in (
            SellerSummary,
            JobError,
            CreateResearchResponse,
            ResearchJobResponse,
            AmazonCandidateResponse,
            ReviewItemResponse,
            ReviewItemsPageResponse,
            ExportJobResponse,
        )
    }

    parts = [
        HEADER.rstrip(),
        render_job_status(),
        render_interface(SellerSummary, models),
        render_interface(JobError, models),
        render_interface(CreateResearchResponse, models),
        render_interface(ResearchJobResponse, models),
        render_interface(AmazonCandidateResponse, models),
        render_interface(ReviewItemResponse, models),
        render_interface(ReviewItemsPageResponse, models),
        render_interface(ExportJobResponse, models),
    ]
    return "\n\n".join(parts) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Sync frontend types from Pydantic schemas")
    parser.add_argument("--check", action="store_true", help="Exit 1 if types.ts would change")
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args()

    new_content = generate()
    if OUTPUT.is_file():
        current = OUTPUT.read_text(encoding="utf-8")
    else:
        current = ""

    if current == new_content:
        if not args.quiet:
            print("frontend types: already up to date")
        return 0

    if args.check:
        print("frontend types: would change (run python3 scripts/sync-api-types.py)", file=sys.stderr)
        return 1

    OUTPUT.write_text(new_content, encoding="utf-8")
    if not args.quiet:
        print(f"Updated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
