// AUTO-GENERATED by scripts/sync-api-types.py — do not edit by hand.
// Regenerate: python3 scripts/sync-api-types.py

export type JobStatus =
  | "PENDING"
  | "SCRAPING"
  | "SCRAPE_FAILED"
  | "AI_INFERENCE"
  | "AI_FAILED"
  | "AWAITING_REVIEW"
  | "APPROVED"
  | "REJECTED"
  | "EXPORTED";

export interface SellerSummary {
  shopee_shop_url: string;
  display_name: string | null;
}

export interface JobError {
  code: string;
  message: string;
}

export interface CreateResearchResponse {
  job_id: string;
  status: JobStatus;
  progress_pct: number;
}

export interface ResearchJob {
  job_id: string;
  status: JobStatus;
  progress_pct: number;
  seller: SellerSummary;
  item_count: number;
  error: JobError | null;
  created_at: string;
  updated_at: string;
}

export interface AmazonCandidate {
  candidate_id: string;
  rank: number;
  asin: string;
  amazon_url: string;
  title: string;
  confidence: number;
}

export interface ReviewItem {
  item_id: string;
  shopee_item_id: string;
  title: string;
  image_url: string;
  shopee_item_url: string;
  sold_count: number | null;
  candidates: AmazonCandidate[];
  decision: string | null;
}

export interface ReviewItemsPage {
  items: ReviewItem[];
  page: number;
  page_size: number;
  total: number;
}

export interface ExportJobResponse {
  job_id: string;
  exported_count: number;
  skipped_count: number;
}
