from enum import Enum


class JobStatus(str, Enum):
    PENDING = "PENDING"
    SCRAPING = "SCRAPING"
    SCRAPE_FAILED = "SCRAPE_FAILED"
    AI_INFERENCE = "AI_INFERENCE"
    AI_FAILED = "AI_FAILED"
    AWAITING_REVIEW = "AWAITING_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXPORTED = "EXPORTED"
